DESIGN=WTF
DESDIR=C:\Users\robin.yuan\OneDrive - General Fusion Inc\Desktop\First_FPGA_TEST\designer\WTF
TARGET_DIR=C:\Users\robin.yuan\OneDrive - General Fusion Inc\Desktop\First_FPGA_TEST\designer\WTF
FAM=SmartFusion2
DIE=PA4M2500_N
PACKAGE=vf256
PINRPT_BY_NAME=1
PINRPT_BY_NUMBER=1
BANK_REPORT=1
IOREG_REPORT=1
